In [1]:
import numpy as np

def householder_qr(A):
    """
    Computes QR decomposition of an m x n matrix A using Householder transformations.
    :param A: Input matrix (m x n)
    :return: Q (orthogonal matrix), R (upper triangular matrix)
    """
    m, n = A.shape
    I = np.eye(m)
    Q = I.copy()
    R = A.copy()

    for j in range(min(m, n)):
        x = R[j:m, j]  # Select j-th column to be transformed

        v = -np.sign(x[0] + np.finfo(float).eps) * np.linalg.norm(x) * np.eye(m - j, 1) - x.reshape(-1, 1)  # Compute Householder vector

        if np.linalg.norm(v) > 0:  # Apply transformation only if v is nonzero
            v = v / np.linalg.norm(v)
            H = np.eye(m)
            H[j:m, j:m] -= 2 * (v @ v.T)  # Householder transformation

            R = H @ R  # Update R
            Q = Q @ H  # Accumulate Q

    return Q, R

def householder_tridiag(A):
    """
    Reduces a square matrix A to upper-Hessenberg form using Householder transformations.
    If A is symmetric, the result is a tridiagonal matrix.
    :param A: Input square matrix (n x n)
    :return: Transformed matrix in upper-Hessenberg or tridiagonal form
    """
    n = A.shape[0]
    I = np.eye(n)

    for j in range(n - 2):
        x = A[j+1:n, j]  # Select j-th column to be transformed

        v = -np.sign(x[0] + np.finfo(float).eps) * np.linalg.norm(x) * np.eye(n - j - 1, 1) - x.reshape(-1, 1)  # Compute Householder vector

        if np.linalg.norm(v) > 0:  # Apply transformation only if v is nonzero
            v = v / np.linalg.norm(v)
            H = np.eye(n)
            H[j+1:n, j+1:n] -= 2 * (v @ v.T)  # Householder transformation

            A = H @ A @ H  # Apply similarity transformation

    return A

In [2]:
# Example matrix
test_matrix = np.array([[4, 1, -2, 2],
                        [1, 2, 0, 1],
                        [-2, 0, 3, -2],
                        [2, 1, -2, -1]])

# Apply Householder tridiagonalization
tridiag_matrix = householder_tridiag(test_matrix)
print("Tridiagonalized Matrix:")
print(tridiag_matrix)

# Apply Householder QR decomposition
Q, R = householder_qr(test_matrix)
print("Q Matrix from QR Decomposition:")
print(Q)
print("R Matrix from QR Decomposition:")
print(R)


Tridiagonalized Matrix:
[[ 4.00000000e+00 -3.00000000e+00  1.33226763e-16 -9.32587341e-16]
 [-3.00000000e+00  3.33333333e+00 -1.66666667e+00  8.88178420e-17]
 [ 1.33226763e-16 -1.66666667e+00 -1.32000000e+00  9.06666667e-01]
 [-9.32587341e-16 -4.44089210e-17  9.06666667e-01  1.98666667e+00]]
Q Matrix from QR Decomposition:
[[-0.8         0.15096588 -0.57749944  0.06085806]
 [-0.2        -0.90579529  0.07874992  0.36514837]
 [ 0.4        -0.34506487 -0.69562432 -0.4868645 ]
 [-0.4        -0.19409899  0.41999959 -0.79115481]]
R Matrix from QR Decomposition:
[[-5.00000000e+00 -1.60000000e+00  3.60000000e+00 -2.20000000e+00]
 [-1.69601106e-17 -1.85472370e+00 -9.48928404e-01  2.80365210e-01]
 [ 2.68361460e-17 -9.98738714e-17 -1.77187327e+00 -1.04999897e-01]
 [ 2.30850574e-17 -8.81198636e-18  2.97514807e-19  2.25174829e+00]]
