In [20]:
import numpy as np

def sign_function(x):
    if x >= 0:
        return 1
    else:
        return -1

def jacobi(A, epsilon):
    """
    Jacobi method for finding eigenvalues and eigenvectors of a matrix A.

    Args:
    - A (numpy.ndarray): A square matrix (nxn).
    - epsilon (float): The tolerance for convergence.

    Returns:
    - V (numpy.ndarray): Matrix of eigenvectors.
    - D (numpy.ndarray): Diagonal matrix of eigenvalues.
    - iter (int): Number of iterations.
    """
    # Initialize V, D, and parameters:
    D = np.array(A, dtype=np.float64, copy=True)
    n = A.shape[0]
    V = np.eye(n)

    # Calculate row p and column q of the off-diagonal element of greatest magnitude in D:
    matrix = np.tril(np.abs(D - np.diag(np.diag(D))),-1)
    max_value_2d = np.max(matrix)  # Find the max value
    max_index_2d = np.unravel_index(np.argmax(matrix), matrix.shape)
    p, q = max_index_2d

    iter = 1  # counter

    while np.abs(D[p, q]) > epsilon*np.sqrt(np.sum(np.diag(D)**2)/n):  # tol. criteria
        # rotation parameters
        a = (D[q, q] - D[p, p]) / (2 * D[p, q])
        t = sign_function(a) / (np.abs(a) + np.sqrt(a**2 + 1))
        c = 1 / np.sqrt(1 + t**2)
        s = c * t
        R = np.array([[c, s], [-s, c]])

        # Zero out Dpq and Dqp
        D[[p, q], :] = np.dot(R.T, D[[p, q], :])
        D[:, [p, q]] = np.dot(D[:, [p, q]], R)
        V[:, [p, q]] = np.dot(V[:, [p, q]], R)

        # Update row p and column q of the off-diagonal element of greatest magnitude in D:
        matrix = np.tril(np.abs(D - np.diag(np.diag(D))),-1)
        max_value_2d = np.max(matrix)  # Find the max value
        max_index_2d = np.unravel_index(np.argmax(matrix), matrix.shape)
        p, q = max_index_2d

        iter += 1  # counter

    return V, D, iter

In [21]:
# Test matrix A
A = np.array([[2, 1, 3],[1, 2, 5],[3, 5, 2]])

# Set the tolerance epsilon
epsilon = 1e-6

# Call the Jacobi method
V, D, iter = jacobi(A, epsilon)

# Output the results
print("Eigenvectors (V):")
print(V)
print("\nEigenvalues (D):")
print(np.diag(D))  # Eigenvalues are the diagonal elements of D
print("\nNumber of iterations:", iter)
print('-'*40)
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvectors (V) using numpy:")
print(eigenvectors)
print("\nEigenvalues (D) using numpy:")
print(eigenvalues)

Eigenvectors (V):
[[ 0.86089001  0.41847141 -0.28939605]
 [-0.50177052  0.60413273 -0.61907187]
 [-0.08423025  0.6781632   0.73006845]]

Eigenvalues (D):
[ 1.12362622  8.30538185 -3.42900808]

Number of iterations: 8
----------------------------------------
Eigenvectors (V) using numpy:
[[-0.41847145 -0.86088999 -0.28939605]
 [-0.60413271  0.50177055 -0.61907187]
 [-0.67816319  0.08423029  0.73006845]]

Eigenvalues (D) using numpy:
[ 8.30538185  1.12362622 -3.42900808]
