In [35]:
import numpy as np

def unshifted_qr(A, k):
    """
    Unshifted QR Algorithm
    :param A: Input matrix (square matrix)
    :param k: Number of iterations
    :return: Eigenvalues (lam), Eigenvector matrix (Qbar)
    """
    m, n = A.shape
    Q = np.eye(m)
    Qbar = Q.copy()
    R = A.copy()

    for _ in range(k):
        Q, R = np.linalg.qr(R @ Q)  # NumPy QR factorization
        Qbar = Qbar @ Q  # Accumulate Q’s

    lam = np.diag(R @ Q)  # Diagonal elements converge to eigenvalues
    return lam, Qbar



In [36]:
# First matrix
A = np.array([[4, 2, 2, 1],
              [2, -3, 1, 1],
              [2, 1, 3, 1],
              [1, 1, 1, 2]])
lam, Qbar = unshifted_qr(A, 20)
d,V = np.linalg.eig(A)
print("Computed Eigenvalues:", lam)
print("Numpy Eigenvalues:", d)
print("-")
print("Computed Eigenvectors:", Qbar)
print("Numpy Eigenvectors:", V)

Computed Eigenvalues: [ 6.64575131 -3.64575131  1.64557867  1.35442133]
Numpy Eigenvalues: [ 6.64575131 -3.64575131  1.64575131  1.35424869]
-
Computed Eigenvectors: [[ 0.72579562 -0.22093805 -0.59901896  0.25609253]
 [ 0.24192994  0.965828   -0.02478226  0.08962157]
 [ 0.55438732 -0.06060084  0.37817804 -0.7388935 ]
 [ 0.32763596 -0.12120314  0.70536763  0.61678277]]
Numpy Eigenvectors: [[ 0.72579521  0.22093938 -0.59260931  0.27059438]
 [ 0.24193174 -0.96582755 -0.02259388  0.09019813]
 [ 0.55438721  0.06060188  0.36008436 -0.74787799]
 [ 0.32763574  0.12120376  0.72016872  0.59943431]]


In [37]:
def shifted_qr(A, tol, s=None):
    """
    Shifted QR method for computing eigenvalues.
    :param A: Input square matrix
    :param tol: Tolerance for convergence
    :param s: Initial shift (optional)
    :return: Eigenvalues (lam)
    """
    A = A.copy()
    m, n = A.shape
    lam = np.zeros(n)

    if s is None:
        s = A[-1, -1]  # Default shift if not provided
    it = 0
    while m > 1:
        while np.max(np.abs(A[m-1, :m-1])) > tol:
            Q, R = np.linalg.qr(A - s * np.eye(m))
            A = R @ Q + s * np.eye(m)
            s = A[-1, -1]  # Update shift
            it += 1
        lam[m-1] = A[m-1, m-1]  # Store eigenvalue
        m -= 1  # Deflate
        A = A[:m, :m]

    lam[0] = A[0, 0]  # Last remaining eigenvalue
    return lam,it

In [38]:
print("-")
lam2,it = shifted_qr(A, 1e-5)
print("Number of iterations:",it)
print("Computed shifted Eigenvalues:", lam2)
print("Computed unshifted Eigenvalues:", lam)
print("Numpy Eigenvalues:", d)

-
Number of iterations: 9
Computed shifted Eigenvalues: [ 6.64575131 -3.64575131  1.35424869  1.64575131]
Computed unshifted Eigenvalues: [ 6.64575131 -3.64575131  1.64557867  1.35442133]
Numpy Eigenvalues: [ 6.64575131 -3.64575131  1.64575131  1.35424869]


In [39]:
# Second matrix
A = np.array([[2, -12, 12, 12],
              [-5, -1, -5, 1],
              [-1, 7, -7, -7],
              [-3, -5, 1, 9]])
lam, Qbar = unshifted_qr(A, 100)
d,V = np.linalg.eig(A)
print("Matrix 2:")
print("Computed Eigenvalues:", lam)
print("Numpy Eigenvalues:", d)
print("-")
print("-")
print("Computed Eigenvectors:", Qbar)
print("Numpy Eigenvectors:", V)

Matrix 2:
Computed Eigenvalues: [-5.18602606  4.68087214  3.99999983 -0.4948459 ]
Numpy Eigenvalues: [-5.18347642 -0.4948459   4.          4.67832232]
-
-
Computed Eigenvectors: [[ 0.77568204  0.24405502 -0.29401898  0.50230206]
 [ 0.28534319 -0.94847189  0.10913859  0.08407801]
 [-0.47743825 -0.04767438  0.17100299  0.86054509]
 [ 0.29824379  0.1963807   0.93402333 -0.0092563 ]]
Numpy Eigenvectors: [[ 0.77572061  0.66623322 -0.80380475  0.78907549]
 [ 0.28519326 -0.42130804  0.31817271 -0.25140701]
 [-0.47744578 -0.61302685  0.43539424 -0.43218298]
 [ 0.29827482  0.05320637 -0.25118898  0.35689251]]


In [40]:
# Third matrix
A = np.array([[8, 20, -4, -20],
              [3, 1, 3, -3],
              [-5, -13, 3, 13],
              [5, 7, 1, -9]])
lam, Qbar = unshifted_qr(A, 100)
d = np.linalg.eigvals(A)
print("Matrix 3:")
print("Computed Eigenvalues:", lam)
print("Numpy Eigenvalues:", d)
print("-")

Matrix 3:
Computed Eigenvalues: [ 4.00000000e+00 -2.00000000e+00  1.00000000e+00  4.40606103e-15]
Numpy Eigenvalues: [ 4.00000000e+00 -2.00000000e+00  1.00000000e+00 -9.78478367e-15]
-
