# Optional Assignment 3

In [ ]:
import numpy as np

n = 15
graph = (
    (1, 2),
    (1, 9),
    (2, 3),
    (2, 5),
    (2, 7),
    (3, 2),
    (3, 6),
    (3, 8),
    (4, 3),
    (4, 12),
    (5, 1),
    (5, 10),
    (6, 10),
    (6, 11),
    (7, 10),
    (7, 11),
    (8, 4),
    (8, 11),
    (9, 5),
    (9, 6),
    (9, 10),
    (10, 13),
    (11, 15),
    (12, 7),
    (12, 8),
    (12, 11),
    (13, 9),
    (13, 14),
    (14, 10),
    (14, 11),
    (14, 13),
    (14, 15),
    (15, 12),
    (15, 14),
)
matrix = np.zeros((n, n))
for i in graph:
    matrix[i[0]-1][i[1]-1] = 1

print(matrix)

[[0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0.]]


A stochastic matrix is one where the sum of its columns is always one.

## 1. Prove that $G$ is a stochastic matrix
We defined $G$ as $$G_{ij} = \frac qn + \frac{(1-q)A_{ji}}{n_j}$$ where $n_j$ is the sum of the $j$-th row of $A$. Note that $\sum_{i = 1}^n A_{ji}$ is also the sum of the $i$-th row of $A$, therefore
$$
\begin{align}
\sum_{i = 1}^n G_{ij} &= \sum_{i = 1}^n \bigg(\frac qn + \frac{(1-q)A_{ji}}{n_j}\bigg) \\
    &= q + (1-q) \sum_{i = 1}^n \frac{A_{ji}}{n_j} \\
    &= q + (1-q) \\ 
    &= 1
\end{align}
$$