# Optional Assignment 3

A stochastic matrix is one where the sum of its columns is always one.

## 1. Prove that $G$ is a stochastic matrix
We defined $G$ as $$G_{ij} = \frac qn + \frac{(1-q)A_{ji}}{n_j}$$ where $n_j$ is the sum of the $j$-th row of $A$. Note that $\sum_{i = 1}^n A_{ji}$ is also the sum of the $i$-th row of $A$, therefore
$$
\begin{align}
\sum_{i = 1}^n G_{ij} &= \sum_{i = 1}^n \bigg(\frac qn + \frac{(1-q)A_{ji}}{n_j}\bigg) \\
    &= q + (1-q) \sum_{i = 1}^n \frac{A_{ji}}{n_j} \\
    &= q + (1-q) \\ 
    &= 1
\end{align}
$$

## 2. Construct $G$

Let us define the matrix $A$ as

In [205]:
import numpy as np

n = 15
graph = (
    (1, 2), (1, 9),
    (2, 3), (2, 5), (2, 7),
    (3, 2), (3, 6), (3, 8),
    (4, 3), (4, 12),
    (5, 1), (5, 10),
    (6, 10), (6, 11),
    (7, 10), (7, 11),
    (8, 4), (8, 11),
    (9, 5), (9, 6), (9, 10),
    (10, 13),
    (11, 15),
    (12, 7), (12, 8), (12, 11),
    (13, 9), (13, 14),
    (14, 10), (14, 11), (14, 13), (14, 15),
    (15, 12), (15, 14),
)
A = np.zeros((n, n))
for i in graph:
    A[i[0]-1][i[1]-1] = 1

print(A)

[[0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0.]]


Then we compute $G$ accordingly with $q=0.15$

In [206]:
n, q = 15, 0.15
def computeG(matrix):
    G = np.zeros((n, n))
    for j in range(n):
        n_j = np.sum(matrix[j])  
        G[:, j] = q / n + matrix[j] * (1 - q) / n_j  

    return G

def powerMethod(G, iterations=100):
    x = np.random.rand(n)
    x = x / np.linalg.norm(x, ord=1)
    for _ in range(iterations):
        x = np.dot(G, x)
        x = x / np.linalg.norm(x, ord=1)

    return x

G = computeG(A)
p = powerMethod(G)
print(f"Matrix G: \n{G}")
print(f"Matrix p: \n{p}, {np.argmax(p)}")
print(f"Sum of G: {np.sum(G, axis=0)}")

Matrix G: 
[[0.01       0.01       0.01       0.01       0.435      0.01
  0.01       0.01       0.01       0.01       0.01       0.01
  0.01       0.01       0.01      ]
 [0.435      0.01       0.29333333 0.01       0.01       0.01
  0.01       0.01       0.01       0.01       0.01       0.01
  0.01       0.01       0.01      ]
 [0.01       0.29333333 0.01       0.435      0.01       0.01
  0.01       0.01       0.01       0.01       0.01       0.01
  0.01       0.01       0.01      ]
 [0.01       0.01       0.01       0.01       0.01       0.01
  0.01       0.435      0.01       0.01       0.01       0.01
  0.01       0.01       0.01      ]
 [0.01       0.29333333 0.01       0.01       0.01       0.01
  0.01       0.01       0.29333333 0.01       0.01       0.01
  0.01       0.01       0.01      ]
 [0.01       0.01       0.29333333 0.01       0.01       0.01
  0.01       0.01       0.29333333 0.01       0.01       0.01
  0.01       0.01       0.01      ]
 [0.01       0.29333333 0.01 

## 3

In [207]:
q = 0
G = computeG(A)
p = powerMethod(G)
max_p = np.max(p)
print(f"(a) q=0.0 p: {p}, {np.argmax(p)}")

q = 0.5
G = computeG(A)
p = powerMethod(G)
max_p = np.max(p)
print(f"(b) q=0.5 p:\n{p}, {np.argmax(p)}")

(a) q=0.0 p: [0.01544402 0.01158301 0.01158301 0.01544402 0.03088803 0.03088803
 0.03088803 0.03088803 0.08108108 0.11003861 0.11003861 0.08108108
 0.14671815 0.14671815 0.14671815], 14
(b) q=0.5 p:
[0.04673566 0.0540207  0.0540207  0.04673566 0.0536093  0.0536093
 0.0536093  0.0536093  0.06763511 0.09463396 0.09463396 0.06763511
 0.09047144 0.07856906 0.09047144], 9


There are multiple pages with the same probability

## 4 Page 7 Enhancement


In [208]:
q = 0.15
G = computeG(A)
p = powerMethod(G)

for i in ((2, 7), (12, 7)):
    A[i[0]-1][i[1]-1] = 2

G = computeG(A)
doped_p = powerMethod(G)
print(p, np.argmax(p))
print(doped_p, np.argmax(doped_p))
print(p-doped_p)

[0.02682457 0.02986108 0.02986108 0.02682457 0.03958722 0.03958722
 0.03958722 0.03958722 0.07456439 0.10631995 0.10631995 0.07456439
 0.12509164 0.11632789 0.12509164] 12
[0.02599622 0.02847917 0.02622626 0.02393986 0.03763817 0.03901712
 0.05284145 0.03279967 0.0761871  0.11154626 0.10327246 0.07232423
 0.12973813 0.1172885  0.12270539] 12
[ 0.00082835  0.00138191  0.00363482  0.0028847   0.00194905  0.0005701
 -0.01325423  0.00678754 -0.00162271 -0.00522631  0.0030475   0.00224015
 -0.00464649 -0.00096061  0.00238624]


There are barely any changes, in fact, it impacts negatively on page 7 the most. The most benefited by this change are page 3, 8 and 11.

## 5 Removal of Page $10$

In [209]:
# Remove row 10 and column 10 from A
n = 14
A = np.delete(A, 10, axis=0)
A = np.delete(A, 10, axis=1)
G = computeG(A)
p = powerMethod(G)
print(p, np.argmax(p)+1, np.argmin(p)+1)
print(f"Rank of each page is {np.array([i+1 for i in p.argsort().argsort()])}")

[0.03114826 0.03371671 0.03446263 0.0390201  0.04807994 0.05067955
 0.05068841 0.03330096 0.10659126 0.17904984 0.04525503 0.19444461
 0.11131045 0.04225225] 12 1
Rank of each page is [ 1  3  4  5  8  9 10  2 11 13  7 14 12  6]


Best page now is 12, and the worst is 1

## 6 Own Network
Assume $D$

In [ ]:
n = 7
graph = (
    (1, 2),
    (2, 4),
    (3, 2),
    (4, 1),
    (4, 3),
    (4, 5),
    (5, 6),
    (6, 7),
    (7, 4)
)
D = np.zeros((n, n))
for i in graph:
    D[i[0]-1][i[1]-1] = 1

print(D)
G = computeG(D)
p = powerMethod(G)
print(G)
print(p, np.argmax(p)+1, np.argmin(p)+1)
print(f"Rank of each page is {np.array([i+1 for i in p.argsort().argsort()])}")


[[0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0. 0.]]
[[0.02142857 0.02142857 0.02142857 0.3047619  0.02142857 0.02142857
  0.02142857]
 [0.87142857 0.02142857 0.87142857 0.02142857 0.02142857 0.02142857
  0.02142857]
 [0.02142857 0.02142857 0.02142857 0.3047619  0.02142857 0.02142857
  0.02142857]
 [0.02142857 0.87142857 0.02142857 0.02142857 0.02142857 0.02142857
  0.87142857]
 [0.02142857 0.02142857 0.02142857 0.3047619  0.02142857 0.02142857
  0.02142857]
 [0.02142857 0.02142857 0.02142857 0.02142857 0.87142857 0.02142857
  0.02142857]
 [0.02142857 0.02142857 0.02142857 0.02142857 0.02142857 0.87142857
  0.02142857]] [0.10132006 0.19367267 0.10132006 0.28196995 0.10132006 0.10755062
 0.1128466 ]
