# Optional Assignment 3

A stochastic matrix is one where the sum of its columns is always one.

## 1. Prove that $G$ is a stochastic matrix
We defined $G$ as $$G_{ij} = \frac qn + \frac{(1-q)A_{ji}}{n_j}$$ where $n_j$ is the sum of the $j$-th row of $A$. Note that $\sum_{i = 1}^n A_{ji}$ is also the sum of the $i$-th row of $A$, therefore
$$
\begin{align}
\sum_{i = 1}^n G_{ij} &= \sum_{i = 1}^n \bigg(\frac qn + \frac{(1-q)A_{ji}}{n_j}\bigg) \\
    &= q + (1-q) \sum_{i = 1}^n \frac{A_{ji}}{n_j} \\
    &= q + (1-q) \\ 
    &= 1
\end{align}
$$

## 2. Construct $G$

Let us define the matrix $A$ as

In [38]:
import numpy as np

n = 15
graph = (
    (1, 2),
    (1, 9),
    (2, 3),
    (2, 5),
    (2, 7),
    (3, 2),
    (3, 6),
    (3, 8),
    (4, 3),
    (4, 12),
    (5, 1),
    (5, 10),
    (6, 10),
    (6, 11),
    (7, 10),
    (7, 11),
    (8, 4),
    (8, 11),
    (9, 5),
    (9, 6),
    (9, 10),
    (10, 13),
    (11, 15),
    (12, 7),
    (12, 8),
    (12, 11),
    (13, 9),
    (13, 14),
    (14, 10),
    (14, 11),
    (14, 13),
    (14, 15),
    (15, 12),
    (15, 14),
)
A = np.zeros((n, n))
for i in graph:
    A[i[0]-1][i[1]-1] = 1

print(A)

[[0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0.]]


Then we compute $G$ accordingly with $q=0.15$

In [39]:
n, q = 15, 0.15
def computeG():
    G = np.zeros((n, n))
    for i in range(n):
        n_i = sum(A[i])
        for j in range(n):
            if A[i][j]:
                G[i][j] = q/n + (1-q)/n_i
            else:
                G[i][j] = q/n
    return G

G = computeG()
print(f"Matrix G: \n{G}")
print(np.sum(G, axis=1))

Matrix G: 
[[0.01       0.435      0.01       0.01       0.01       0.01
  0.01       0.01       0.435      0.01       0.01       0.01
  0.01       0.01       0.01      ]
 [0.01       0.01       0.29333333 0.01       0.29333333 0.01
  0.29333333 0.01       0.01       0.01       0.01       0.01
  0.01       0.01       0.01      ]
 [0.01       0.29333333 0.01       0.01       0.01       0.29333333
  0.01       0.29333333 0.01       0.01       0.01       0.01
  0.01       0.01       0.01      ]
 [0.01       0.01       0.435      0.01       0.01       0.01
  0.01       0.01       0.01       0.01       0.01       0.435
  0.01       0.01       0.01      ]
 [0.435      0.01       0.01       0.01       0.01       0.01
  0.01       0.01       0.01       0.435      0.01       0.01
  0.01       0.01       0.01      ]
 [0.01       0.01       0.01       0.01       0.01       0.01
  0.01       0.01       0.01       0.435      0.435      0.01
  0.01       0.01       0.01      ]
 [0.01       0.01     

## 3

In [40]:
q = 0
computeG()
print(np.sum(G, axis=1))

q = 0.5
computeG()
print(np.sum(G, axis=1))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


## 4


## 5 Removal of Page $10$

In [41]:
# Remove row 10 and column 10 from A
n = 14
A = np.delete(A, 10, axis=0)
A = np.delete(A, 10, axis=1)
G = computeG()
print(f"Matrix G: \n{G}")

Matrix G: 
[[0.03571429 0.28571429 0.03571429 0.03571429 0.03571429 0.03571429
  0.03571429 0.03571429 0.28571429 0.03571429 0.03571429 0.03571429
  0.03571429 0.03571429]
 [0.03571429 0.03571429 0.20238095 0.03571429 0.20238095 0.03571429
  0.20238095 0.03571429 0.03571429 0.03571429 0.03571429 0.03571429
  0.03571429 0.03571429]
 [0.03571429 0.20238095 0.03571429 0.03571429 0.03571429 0.20238095
  0.03571429 0.20238095 0.03571429 0.03571429 0.03571429 0.03571429
  0.03571429 0.03571429]
 [0.03571429 0.03571429 0.28571429 0.03571429 0.03571429 0.03571429
  0.03571429 0.03571429 0.03571429 0.03571429 0.28571429 0.03571429
  0.03571429 0.03571429]
 [0.28571429 0.03571429 0.03571429 0.03571429 0.03571429 0.03571429
  0.03571429 0.03571429 0.03571429 0.28571429 0.03571429 0.03571429
  0.03571429 0.03571429]
 [0.03571429 0.03571429 0.03571429 0.03571429 0.03571429 0.03571429
  0.03571429 0.03571429 0.03571429 0.53571429 0.03571429 0.03571429
  0.03571429 0.03571429]
 [0.03571429 0.03571429

## 6 Own Network
Assume $D$

In [ ]:
n = 15
graph = (
    (1, 2),
    (, ),
    (, ),
    (, ),
    (, ),
    (, ),
    (, ),
    (, ),
    (, ),
    (, 2),
    (, ),
    (, 0),
    (, 0),
    (, 1),
    (, 0),
    (, 1),
    (, ),
    (, 1),
    (, ),
    (, ),
    (, 0),
    (, 3),
    (, 5),
    (, ),
    (, ),
    (, 1),
    (, ),
    (, 4),
    (, 0),
    (, 1),
    (, 3),
    (, 5),
    (, 2),
    (, 4),
)
D = np.zeros((n, n))