# Optional Assignment 3

A stochastic matrix is one where the sum of its columns is always one.

## 1. Prove that $G$ is a stochastic matrix
We defined $G$ as $$G_{ij} = \frac qn + \frac{(1-q)A_{ji}}{n_j}$$ where $n_j$ is the sum of the $j$-th row of $A$. Note that $\sum_{i = 1}^n A_{ji}$ is also the sum of the $i$-th row of $A$, therefore
$$
\begin{align}
\sum_{i = 1}^n G_{ij} &= \sum_{i = 1}^n \bigg(\frac qn + \frac{(1-q)A_{ji}}{n_j}\bigg) \\
    &= q + (1-q) \sum_{i = 1}^n \frac{A_{ji}}{n_j} \\
    &= q + (1-q) \\ 
    &= 1
\end{align}
$$

## 2. Construct $G$

Let us define the matrix $A$ as

In [32]:
import numpy as np

n = 15
graph = (
    (1, 2), (1, 9),
    (2, 3), (2, 5), (2, 7),
    (3, 2), (3, 6), (3, 8),
    (4, 3), (4, 12),
    (5, 1), (5, 10),
    (6, 10), (6, 11),
    (7, 10), (7, 11),
    (8, 4), (8, 11),
    (9, 5), (9, 6), (9, 10),
    (10, 13),
    (11, 15),
    (12, 7), (12, 8), (12, 11),
    (13, 9), (13, 14),
    (14, 10), (14, 11), (14, 13), (14, 15),
    (15, 12), (15, 14),
)
A = np.zeros((n, n))
for i in graph:
    A[i[0]-1][i[1]-1] = 1

print(A)

[[0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0.]]


Then we compute $G$ accordingly with $q=0.15$

In [66]:
n, q = 15, 0.15
def computeG():
    G = np.zeros((n, n))
    for j in range(n):
        n_j = np.sum(A[j])  
        G[:, j] = q / n + A[j] * (1 - q) / n_j  

    return G

def powerMethod(G, iterations=100):
    x = np.random.rand(n)
    x = x / np.linalg.norm(x, ord=1)
    for _ in range(iterations):
        x = np.dot(G, x)
        x = x / np.linalg.norm(x, ord=1)

    return x

G = computeG()
p = powerMethod(G)
print(f"Matrix G: \n{G}")
print(f"Matrix p: \n{p}, {np.argmax(p)}")
print(f"Sum of G: {np.sum(G, axis=0)}")

Matrix G: 
[[0.01       0.01       0.01       0.01       0.435      0.01
  0.01       0.01       0.01       0.01       0.01       0.01
  0.01       0.01       0.01      ]
 [0.435      0.01       0.29333333 0.01       0.01       0.01
  0.01       0.01       0.01       0.01       0.01       0.01
  0.01       0.01       0.01      ]
 [0.01       0.29333333 0.01       0.435      0.01       0.01
  0.01       0.01       0.01       0.01       0.01       0.01
  0.01       0.01       0.01      ]
 [0.01       0.01       0.01       0.01       0.01       0.01
  0.01       0.435      0.01       0.01       0.01       0.01
  0.01       0.01       0.01      ]
 [0.01       0.29333333 0.01       0.01       0.01       0.01
  0.01       0.01       0.29333333 0.01       0.01       0.01
  0.01       0.01       0.01      ]
 [0.01       0.01       0.29333333 0.01       0.01       0.01
  0.01       0.01       0.29333333 0.01       0.01       0.01
  0.01       0.01       0.01      ]
 [0.01       0.29333333 0.01 

## 3

In [69]:
q = 0
G = computeG()
p = powerMethod(G)
max_p = np.max(p)
print(f"(a) q=0.0 p: {p}, {np.argmax(p)}")

q = 0.5
G = computeG()
p = powerMethod(G)
max_p = np.max(p)
print(f"(b) q=0.5 p:\n{p}, {np.argmax(p)}")

(a) q=0.0 p: [0.01544402 0.01158301 0.01158301 0.01544402 0.03088803 0.03088803
 0.03088803 0.03088803 0.08108108 0.11003861 0.11003861 0.08108108
 0.14671815 0.14671815 0.14671815], 13
(b) q=0.5 p:
[0.04673566 0.0540207  0.0540207  0.04673566 0.0536093  0.0536093
 0.0536093  0.0536093  0.06763511 0.09463396 0.09463396 0.06763511
 0.09047144 0.07856906 0.09047144], 9


There are multiple pages with the same probability

## 4


In [ ]:
graph = graph + 

## 5 Removal of Page $10$

In [5]:
# Remove row 10 and column 10 from A
n = 14
A = np.delete(A, 10, axis=0)
A = np.delete(A, 10, axis=1)
G = computeG()
print(f"Matrix G: \n{G}")

Matrix G: 
[[0.03571429 0.28571429 0.03571429 0.03571429 0.03571429 0.03571429
  0.03571429 0.03571429 0.28571429 0.03571429 0.03571429 0.03571429
  0.03571429 0.03571429]
 [0.03571429 0.03571429 0.20238095 0.03571429 0.20238095 0.03571429
  0.20238095 0.03571429 0.03571429 0.03571429 0.03571429 0.03571429
  0.03571429 0.03571429]
 [0.03571429 0.20238095 0.03571429 0.03571429 0.03571429 0.20238095
  0.03571429 0.20238095 0.03571429 0.03571429 0.03571429 0.03571429
  0.03571429 0.03571429]
 [0.03571429 0.03571429 0.28571429 0.03571429 0.03571429 0.03571429
  0.03571429 0.03571429 0.03571429 0.03571429 0.28571429 0.03571429
  0.03571429 0.03571429]
 [0.28571429 0.03571429 0.03571429 0.03571429 0.03571429 0.03571429
  0.03571429 0.03571429 0.03571429 0.28571429 0.03571429 0.03571429
  0.03571429 0.03571429]
 [0.03571429 0.03571429 0.03571429 0.03571429 0.03571429 0.03571429
  0.03571429 0.03571429 0.03571429 0.53571429 0.03571429 0.03571429
  0.03571429 0.03571429]
 [0.03571429 0.03571429

## 6 Own Network
Assume $D$

In [6]:
n = 15
graph = (
    (1, 2),
    (, ),
    (, ),
    (, ),
    (, ),
    (, ),
    (, ),
    (, ),
    (, ),
    (, 2),
    (, ),
    (, 0),
    (, 0),
    (, 1),
    (, 0),
    (, 1),
    (, ),
    (, 1),
    (, ),
    (, ),
    (, 0),
    (, 3),
    (, 5),
    (, ),
    (, ),
    (, 1),
    (, ),
    (, 4),
    (, 0),
    (, 1),
    (, 3),
    (, 5),
    (, 2),
    (, 4),
)
D = np.zeros((n, n))

SyntaxError: invalid syntax (284539931.py, line 4)